### ISSUE TITLE
Affected strategy analyze .class files when target dir not ignored

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#165]
##### Issue Overview

Affected strategy analyze `.class` files when target dir not ignored from git (`.gitignore`) and this causes an exception: 

```
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Unable to analyze source file /Users/alex/git/stdemo/target/classes/org/superbiz/A.class
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:665)
```
##### Expected Behaviour

`.class` files should be ignored.

##### Current Behaviour

Exception is thrown.

##### Steps To Reproduce
1. Clone https://github.com/lordofthejars/stdemo
2. Edit `.gitignore` and comment `target/` line using `#`
3. Run `mvn clean test -Dsmart.testing="affected"`

**Comment by MatousJobanek** [comment]
I tried the reproduce the issue and it passed. There was a warning, but different one. I got this:
```
[WARNING] Corrupted stdin stream in forked JVM 1. See the dump file /home/mjobanek/tmp/stdemo/target/surefire-reports/2017-09-22T12-47-00_256-jvmRun1.dumpstream
```
and the content of the file:
```
# Created on 2017-09-22T12:47:01.799
Corrupted stdin stream in forked JVM 1. Stream '[INFO] [Smart Testing Extension] Applied strategies: [affected]'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '[INFO] [Smart Testing Extension] Applied strategies: [affected]'.
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
        at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
        at java.lang.Thread.run(Thread.java:745)


# Created on 2017-09-22T12:47:01.801
Corrupted stdin stream in forked JVM 1. Stream '[INFO] [Smart Testing Extension] Applied usage: [selecting]'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '[INFO] [Smart Testing Extension] Applied usage: [selecting]'.
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:469)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:191)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:158)
        at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:87)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by bartoszmajsak** [comment]
That's exactly why I brought https://issues.apache.org/jira/browse/SUREFIRE-1359 to the table a while back :)

**Comment by MatousJobanek** [comment]
Ok, I just reproduced it - sorry :-)
I didn't notice that I had `target/` entry also in the global `.gitignore` file

**Comment by bartoszmajsak** [comment]
I think it's because the build is executing in the forked surefire process and we share I/O with the surefire - and surefire uses to communicate between booter and fork runner.
