### ISSUE TITLE
Occasional IllegalStateException when running test-bed functional tests

### ISSUE THREAD

**Issue by MatousJobanek** [arquillian/smart-testing#293]
##### Issue Overview

Sometimes when the functional test suite is executed locally, it throws IllegalStateException:
```
should_not_install_extension_when_only_clean_goal_is_used(org.arquillian.smart.testing.ftest.configuration.SkipTestExecutionFunctionalTest)  Time elapsed: 3.412 sec  <<< ERROR!
java.lang.IllegalStateException: Execution of a Maven build has failed
    at org.arquillian.smart.testing.ftest.configuration.SkipTestExecutionFunctionalTest.should_not_install_extension_when_only_clean_goal_is_used(SkipTestExecutionFunctionalTest.java:100)
Caused by: org.apache.maven.shared.invoker.MavenInvocationException: Error configuring command-line. Reason: Maven executable not found at: /home/bartek/code/redhat/arquillian/smart-testing/smart-testing/functional-tests/test-bed/target/resolver-maven/516923b3955b6035ba6b0a5b031fbd8b/apache-maven-3.3.9/bin/mvn
    at org.arquillian.smart.testing.ftest.configuration.SkipTestExecutionFunctionalTest.should_not_install_extension_when_only_clean_goal_is_used(SkipTestExecutionFunctionalTest.java:100)
Caused by: org.apache.maven.shared.invoker.CommandLineConfigurationException: Maven executable not found at: /home/bartek/code/redhat/arquillian/smart-testing/smart-testing/functional-tests/test-bed/target/resolver-maven/516923b3955b6035ba6b0a5b031fbd8b/apache-maven-3.3.9/bin/mvn
    at org.arquillian.smart.testing.ftest.configuration.SkipTestExecutionFunctionalTest.should_not_install_extension_when_only_clean_goal_is_used(SkipTestExecutionFunctionalTest.java:100)
```

This is probably caused by a combination of [SWR implementation](https://github.com/shrinkwrap/resolver/blob/master/maven/impl-maven-embedded/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/embedded/DistributionStageImpl.java#L53-L67) with several forks the test suite is running in.  When one fork starts extracting the archive file and second fork check if the directory is already existing there, then it sees that it's there and continues to Maven invocation. But the archive is not entirely extracted, therefore the Maven invocation fails. 
There is another potential problem - with the downloads. In our case, it doesn't happen because the archive is already downloaded and cached.

**Comment by MatousJobanek** [comment]
Fixed and closed via https://github.com/arquillian/smart-testing/pull/303
