### ISSUE TITLE
java.lang.NoSuchMethodError is thrown in case of not defining surefire

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/smart-testing#69]
##### Issue Overview

`java.lang.NoSuchMethodError` is thrown in case of not defining surefire.

##### Expected Behaviour

Work with defaults

##### Current Behaviour

A `java.lang.NoSuchMethodError` is exception is thrown 

```
Caused by: java.lang.NoSuchMethodError: org.apache.maven.surefire.providerapi.ProviderParameters.getProviderProperties()Ljava/util/Map;
	at org.arquillian.smart.testing.surefire.provider.ProviderParametersParser.getProperty(ProviderParametersParser.java:46)
	at org.arquillian.smart.testing.surefire.provider.info.JUnitCoreProviderInfo.isAnyConcurrencySelected(JUnitCoreProviderInfo.java:47)
	at org.arquillian.smart.testing.surefire.provider.info.JUnitCoreProviderInfo.isApplicable(JUnitCoreProviderInfo.java:33)
	at org.arquillian.smart.testing.surefire.provider.ProviderList.autoDetectOneProvider(ProviderList.java:37)
	at org.arquillian.smart.testing.surefire.provider.ProviderList.resolve(ProviderList.java:23)
	at org.arquillian.smart.testing.surefire.provider.SmartTestingSurefireProvider.<init>(SmartTestingSurefireProvider.java:25)
```

##### Steps To Reproduce
1. Execute smart testing on project with a `pom.xml` without defining `surefire` such as https://github.com/lordofthejars/jaxrs-analyzer.git
2. Exception is thrown.

**Comment by lordofthejars** [comment]
The problem is that default `surefire` plugin used in case user does not set it, uses an old version which has some compatibility issues.

Maybe the solution could be is to get registered `surefire` version, and if it is not supported log it and throw a controlled exception.

**Comment by bartoszmajsak** [comment]
> Maybe the solution could be is to get registered surefire version, and if it is not supported log it and throw a controlled exception.

Yes, we have to ensure we are using the compatible version of Surefire. If we could avoid exceptions such as `java.lang.NoSuchMethodError`, and provide meaningful information not only about the issue but also with a hint for the user on how he could resolve, that would be optimal.

**Comment by lordofthejars** [comment]
Great I ll do it tomorrow morning, so another PR for mvn_ext branch :)

**Comment by MatousJobanek** [comment]
I was off when you created the issue yesterday, so sorry for late response. Yeah, the cause is the version of surefire/failsafe. When you update to the 2.19.1, then it should work. 

> Yes, we have to ensure we are using the compatible version of Surefire. If we could avoid exceptions such as java.lang.NoSuchMethodError, and provide meaningful information not only about the issue but also with a hint for the user on how he could resolve, that would be optimal.

+1 I don't know why I haven't implemented yet, but I'm 100% sure that I had it in my mind... :-)
